# Generated by Django 6.0.6 on 2026-06-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='internship',
            index=models.Index(fields=['deadline'], name='internships_deadlin_509b56_idx'),
        ),
    ]
