# Generated by Django 6.0.6 on 2026-06-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_internship_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='internship',
            name='internships_deadlin_509b56_idx',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='deadline',
        ),
    ]
