# Generated by Django 6.0.6 on 2026-06-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
    ]
